Algoritmo "Exercicio 07"
// Algoritmos e Programação
// Professor   : Gustavo Vinhal
// Autor(a)    : Gustavo Passinato Neves
// Data atual  : 5/17/2022
Var
// Seção de Declarações das variáveis 
   contador: inteiro


Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
   para contador de 0 ate 100 faca
        escreval("Se eu não fizer as atividades de Algoritmos e Programação, reprovarei.")
   fimpara

Fimalgoritmo